name: innosoft_task
description: Innosoft Task

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  scoped_model: ^1.0.1
  http: ^0.12.0+2
  cached_network_image: ^0.7.0
  intl_translation: ^0.17.4
  intl: ^0.15.7
  #connectivity: ^0.4.3+1
  connectivity: ^0.4.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/5TRrpRAGc.png
    - assets/5TRrpRAGc@2x.png
    - assets/5TRrpRAGc@3x.png
    - assets/FHg3gVUXuDRecedpcuUnCT.png
    - assets/FHg3gVUXuDRecedpcuUnCT@2x.png
    - assets/FHg3gVUXuDRecedpcuUnCT@3x.png
    - assets/Fill67.png
    - assets/Fill67@2x.png
    - assets/Fill67@3x.png
    - assets/Glyph.png
    - assets/Glyph@2x.png
    - assets/Glyph@3x.png
    - assets/Glyph2.png
    - assets/Glyph2@2x.png
    - assets/Glyph2@3x.png
    - assets/Glyph3.png
    - assets/Glyph3@2x.png
    - assets/Glyph3@3x.png
    - assets/Glyph4.png
    - assets/Glyph4@2x.png
    - assets/Glyph4@3x.png
    - assets/Glyph5.png
    - assets/Glyph5@2x.png
    - assets/Glyph5@3x.png
    - assets/Group544.png
    - assets/Group544@2x.png
    - assets/Group544@3x.png
    - assets/Group545.png
    - assets/Group545@2x.png
    - assets/Group545@3x.png
    - assets/Group546.png
    - assets/Group546@2x.png
    - assets/Group546@3x.png
    - assets/Group5442.png
    - assets/Group5442@2x.png
    - assets/Group5442@3x.png
    - assets/Icon.png
    - assets/Icon@2x.png
    - assets/Icon@3x.png
    - assets/Icon2.png
    - assets/Icon2@2x.png
    - assets/Icon2@3x.png
    - assets/Icon3.png
    - assets/Icon3@2x.png
    - assets/Icon3@3x.png
    - assets/Icon5.png
    - assets/Icon5@2x.png
    - assets/Icon5@3x.png
    - assets/Icon6.png
    - assets/Icon6@2x.png
    - assets/Icon6@3x.png
    - assets/Image.png
    - assets/Image@2x.png
    - assets/Image@3x.png
    - assets/img.png
    - assets/img@2x.png
    - assets/img@3x.png
    - assets/img2.png
    - assets/img2@2x.png
    - assets/img2@3x.png
    - assets/img3.png
    - assets/img3@2x.png
    - assets/img3@3x.png
    - assets/logo-club-foot-png-2.png
    - assets/logo-club-foot-png-2@2x.png
    - assets/logo-club-foot-png-2@3x.png
    - assets/Path171.png
    - assets/Path171@2x.png
    - assets/Path171@3x.png
    - assets/Symbol2–1.png
    - assets/Symbol2–1@2x.png
    - assets/Symbol2–1@3x.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
